### ISSUE TITLE
When I run the "cvc" command I get an error

### ISSUE THREAD

**Issue by sedatigrek** [rizal72/Cozmo-Voice-Commands#6]
When I run the "cvc" command, I get the following error

Cozmo-Voice-Commands (CvC) - Version 0.7.0 - Riccardo Sallusti (http://riccardosallusti.it)
2023-04-08 12:33:52,146 cozmo.general INFO     App connection established. sdk_version=1.4.10 cozmoclad_version=3.4.0 app_build_version=00003.00004.00000
2023-04-08 12:33:52,150 cozmo.general INFO     Found robot id=1
2023-04-08 12:33:52,171 cozmo.general INFO     Connected to Android device serial=QBK6R20623003937
2023-04-08 12:33:52,960 cozmo.general INFO     Robot id=1 serial=45a22ffc initialized OK

loading languages files...
2023-04-08 12:33:52,991 cozmo.general INFO     Shutting down connection
2023-04-08 12:33:52,993 cozmo.general INFO     Android serial=QBK6R20623003937 disconnected.
Traceback (most recent call last):
  File "C:\Users\14B\AppData\Local\Programs\Python\Python37-32\Scripts\cvc-script.py", line 11, in <module>
    load_entry_point('cvc==0.7.0', 'console_scripts', 'cvc')()
  File "c:\users\14b\appdata\local\programs\python\python37-32\lib\site-packages\cvc\cozmo_voice_commands.py", line 50, in main
    cozmo.run_program(run)
  File "C:\Users\14B\AppData\Roaming\Python\Python37\site-packages\cozmo\run.py", line 849, in run_program
    connect(wrapper, conn_factory=conn_factory, connector=connector)
  File "C:\Users\14B\AppData\Roaming\Python\Python37\site-packages\cozmo\run.py", line 605, in connect
    return _connect_sync(f, conn_factory, connector)
  File "C:\Users\14B\AppData\Roaming\Python\Python37\site-packages\cozmo\run.py", line 530, in _connect_sync
    f(base._SyncProxy(coz_conn))
  File "C:\Users\14B\AppData\Roaming\Python\Python37\site-packages\cozmo\run.py", line 835, in wrapper
    f(robot)
  File "c:\users\14b\appdata\local\programs\python\python37-32\lib\site-packages\cvc\cozmo_voice_commands.py", line 81, in run
    load_jsons()
  File "c:\users\14b\appdata\local\programs\python\python37-32\lib\site-packages\cvc\cozmo_voice_commands.py", line 110, in load_jsons
    languages.append(json.load(json_file))
  File "c:\users\14b\appdata\local\programs\python\python37-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "c:\users\14b\appdata\local\programs\python\python37-32\lib\encodings\cp1254.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9e in position 257: character maps to <undefined>

**Comment by rizal72** [comment]
Python version 3.6 is mandatory. Please read the updated readme for instructions. Thanks
